### ISSUE TITLE
package.json doesn't... work? wat

### ISSUE THREAD

**Issue by leostratus** [leostratus/interdisciplinary-programming#2]
Despite having a perfectly valid package.json file, packages still need to manually installed via npm install at the command line.

**Comment by katieannemills** [comment]
I definitely saw this behavior on your machine, but I can't reproduce it on mine - for me, hiding `/node_modules` and doing an `npm install` fetched everything and the app launched correctly.

**Comment by abbycabs** [comment]
definitely working fine for me...

**Comment by leostratus** [comment]
Assume that if you can't repro it, it was fixed in some previous version or my local copy had something wrong with it. Closing!
