### ISSUE TITLE
Error 1102: Login failed after fresh signup

### ISSUE THREAD

**Issue by leostratus** [leostratus/interdisciplinary-programming#23]

**Comment by leostratus** [comment]
Need to investigate repro conditions, unclear.

**Comment by leostratus** [comment]
Cannot POST /logout - may be related, can't click this 'back to safety' after this thing bails.

Also, no output from the app. Maybe good ol' fashioned explicit logging?

**Comment by katieannemills** [comment]
Some server-side console logs now spit out info about what is going wrong during login after profile creation; plz post logs here next time this is seen.

**Comment by katieannemills** [comment]
Console logging indicates a login error and user respectively:

```
[Error: Failed to serialize user into session]
null
```

It seems that a race condition was being created between inserting the new user into the DB, and looking for that user in the DB to log them in.  Moving login into the callback to DB insertion seems like a good move; 22 consecutive profile creations were successful after doing this.  This error seemed to happen on the ~10% level previously, so p(22 success & 0 failure | bug still active) < 10% ; going to close now, reopen if needed.

**Comment by katieannemills** [comment]
Oops, that last commit didn't have the right stuff added to it - the next one does.
