### ISSUE TITLE
Make sure we're gzipping content served from our server

### ISSUE THREAD

**Issue by leostratus** [leostratus/interdisciplinary-programming#36]

**Comment by katieannemills** [comment]
Unfortunately, after a while I started getting this complaint:

```
net::ERR_CONTENT_DECODING_FAILED 
```

WRT the static css, which apparently means this isn't getting gzipped even though the header claims it is.  Removed compression for now and reopening issue :/

**Comment by katieannemills** [comment]
Turns out this looked like it worked at first b/c the uncompressed CSS was cached.  There appears to be some sensitivity to order-of-operations between compressing and minifying - putting the compression middleware first seems to solve the problem.

**Comment by katieannemills** [comment]
fixed in 7c4863316ec7a4451647b7b51b2f843986993c64
